# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IvoryiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IvoryiOS
  pod 'AFNetworking'
  pod 'Alamofire'
  pod 'PayPal-iOS-SDK'
  pod 'SDWebImage'
  pod 'SideMenu'
  pod 'Stripe'
  pod 'SwiftyJSON'
  pod 'SwiftKeychainWrapper'

  target 'IvoryiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IvoryiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
